name: bootleg_instagram
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Emblem_ACVI_Handler_Walter.webp
    - assets/You.jpg
    - assets/Bonnie.jpg
    - assets/Eric.jpg
    - assets/Ida.jpg
    - assets/Jordan.jpg
    - assets/Tracey.jpg
